notx/src/notx-main/src/main/java/net/notx/web/DomainStatisticsActionBean.java
package net.notx.web;

import com.googlecode.charts4j.*;
import java.util.Map.Entry;
import java.util.*;
import net.notx.cassandra.CassandraException;
import net.notx.core.entities.SentNotification;
import net.notx.core.service.StatsService;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.integration.spring.SpringBean;

/**
 *
 * @author Filip Nguyen
 */
public class DomainStatisticsActionBean extends NotxActionBean {

    @SpringBean
    private StatsService statsService;
    
    private Map<String, Set<SentNotification>> statisticsByDomain = new HashMap<String, Set<SentNotification>>();
    private String graph;
    

    public Resolution show() throws CassandraException {
        statisticsByDomain = statsService.loadStatsByDomain();


        setGraph(createGraph(statisticsByDomain));
        return new ForwardResolution("/domainStats.jsp");
    }

    private String createGraph(
            Map<String, Set<SentNotification>> statsByDomain) {
        List<Color> colors = new ArrayList<Color>();
        List<String> engines = new ArrayList<String>(getPresentEngines());
        List<String> domains = new ArrayList<String>(statsByDomain.keySet());
        colors.add(Color.GREEN);
        colors.add(Color.BLACK);
        colors.add(Color.BISQUE);
        colors.add(Color.BLANCHEDALMOND);
        colors.add(Color.CADETBLUE);

        List<BarChartPlot> plots = new ArrayList<BarChartPlot>();

        int i = 0;
        for (String engine : engines) {
            List<Number> data = new ArrayList<Number>(countEnginePresenceByDomain(engine));

            BarChartPlot plot = Plots.newBarChartPlot(
                    Data.newData(data), colors.get(i), engine);

            plots.add(plot);
            i++;
        }

        BarChart chart = GCharts.newBarChart(plots);
        AxisStyle axisStyle = AxisStyle.newAxisStyle(Color.BLACK, 13, AxisTextAlignment.CENTER);
        AxisLabels score = AxisLabelsFactory.newAxisLabels("Number of notifications", 50.0);
        score.setAxisStyle(axisStyle);
        AxisLabels year = AxisLabelsFactory.newAxisLabels("Domain", 50.0);
        year.setAxisStyle(axisStyle);
        chart.addXAxisLabels(AxisLabelsFactory.newAxisLabels(domains));
        chart.addYAxisLabels(AxisLabelsFactory.newNumericRangeAxisLabels(0, 20));
        chart.addYAxisLabels(score);
        chart.addXAxisLabels(year);

        chart.setSize(600, 450);
        chart.setBarWidth(100);
        chart.setSpaceWithinGroupsOfBars(20);
        chart.setDataStacked(true);
        chart.setTitle("Notification statistics", Color.BLACK, 16);
        chart.setGrid(100, 10, 3, 2);
        chart.setBackgroundFill(Fills.newSolidFill(Color.WHITE));
        LinearGradientFill fill = Fills.newLinearGradientFill(0, Color.WHITE, 100);
        fill.addColorAndOffset(Color.WHITE, 0);
        chart.setAreaFill(fill);

        return chart.toURLForHTML();

    }

    private List<Number> countEnginePresenceByDomain(String engine) {
        List<Number> counts = new ArrayList<Number>();


        for (Entry<String, Set<SentNotification>> stat : statisticsByDomain.entrySet()) {
            int i = 0;
            for (SentNotification sns : stat.getValue()) {
                if (sns.getEngine().equals(engine)) {
                    i++;
                }
            }
            counts.add(i * 5);
        }
        return counts;
    }

    private Set<String> getPresentEngines() {
        Set<String> engines = new HashSet<String>();

        for (Entry<String, Set<SentNotification>> stat : statisticsByDomain.entrySet()) {
            for (SentNotification sns : stat.getValue()) {
                engines.add(sns.getEngine());
            }
        }
        return engines;
    }

    /**
     * @param statisticsByDomain the statisticsByDomain to set
     */
    public void setStatisticsByDomain(Map<String, Set<SentNotification>> statisticsByDomain) {
        this.statisticsByDomain = statisticsByDomain;
    }

    /**
     * @return the statisticsByDomain
     */
    public Map<String, Set<SentNotification>> getStatisticsByDomain() {
        return statisticsByDomain;
    }

    /**
     * @param graph the graph to set
     */
    public void setGraph(String graph) {
        this.graph = graph;
    }

    /**
     * @return the graph
     */
    public String getGraph() {
        return graph;
    }
}

notx/src/notx-main/src/main/java/net/notx/web/ErrorActionBean.java
package net.notx.web;

import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;


/**
 *
 * @author Filip Nguyen
 */
public class ErrorActionBean extends NotxActionBean {

    private String cassandraSettings;
    private String jmsSettings;

    public Resolution cassandra() {
        //cassandraSettings = context.getCassandraSetting();
        return new ForwardResolution("/cassandraDown.jsp");
    }

    public Resolution jms() {
        //jmsSettings = context.getJmsSettings();
        return new ForwardResolution("/jmsDown.jsp");
    }

    public String getCassandraSettings() {
        return cassandraSettings;
    }

    public void setCassandraSettings(String cassandraSettings) {
        this.cassandraSettings = cassandraSettings;
    }

    public String getJmsSettings() {
        return jmsSettings;
    }

    public void setJmsSettings(String jmsSettings) {
        this.jmsSettings = jmsSettings;
    }
}

notx/src/notx-main/src/main/java/net/notx/web/ErrorViewActionBean.java
package net.notx.web;

import java.util.ArrayList;
import java.util.List;
import net.notx.cassandra.CassandraException;
import net.notx.client.message.AbstractMessage;
import net.notx.client.message.AbstractNotificationMessage;
import net.notx.client.message.HandlingFailMessage;
import net.notx.core.queue.QueueService;
import net.notx.core.service.StatsService;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.integration.spring.SpringBean;
import org.apache.commons.lang.exception.ExceptionUtils;

/**
 *
 * @author Filip Nguyen
 */
public class ErrorViewActionBean extends NotxActionBean {

    @SpringBean
    private StatsService statsService;
    @SpringBean
    private QueueService queueService;
    private List<HandlingFailMessage> notificationFails = new ArrayList<HandlingFailMessage>();
    private List<HandlingFailMessage> otherFails = new ArrayList<HandlingFailMessage>();
    private HandlingFailMessage detail = new HandlingFailMessage();
    private String theFailStackTrace = null;

    public Resolution show() throws CassandraException {
        List<HandlingFailMessage> hfms = statsService.listFailMessages();
        for (HandlingFailMessage hf : hfms) {
            if (hf.getSqsMessage() instanceof AbstractNotificationMessage) {
                notificationFails.add(hf);
            } else {
                otherFails.add(hf);
            }
        }
        return new ForwardResolution("/errorView.jsp");
    }

    public Resolution resendNotifications() throws CassandraException {
        resendFails(notificationFails);
        return show();
    }

    public Resolution resendOthers() throws CassandraException {
        resendFails(otherFails);
        return show();
    }

    public Resolution viewDetail() {
        detail = statsService.loadFailMessages(detail.getUid());
        theFailStackTrace = ExceptionUtils.getFullStackTrace(detail.getException());
        return new ForwardResolution("/errorViewDetail.jsp");
    }

    /**
     * Sends back to mq message that is viewed in detail.
     *
     * @return
     */
    public Resolution sendNotificationToMQ() {
        detail = statsService.loadFailMessages(detail.getUid());
        queueService.putMessage((AbstractMessage)detail.getSqsMessage());
        statsService.deleteFailMessage(detail);        
        return show();
    }

    /**
     * Takes fails and resends them into MQ.
     *
     * @param fails
     * @throws CassandraException
     */
    public void resendFails(List<HandlingFailMessage> fails) throws CassandraException {

        for (final HandlingFailMessage hf : fails) {
            queueService.putMessage((AbstractMessage) hf.getSqsMessage());
            statsService.deleteFailMessage(hf);
        }
    }

    public HandlingFailMessage getDetail() {
        return detail;
    }

    public void setDetail(HandlingFailMessage detail) {
        this.detail = detail;
    }

    public void setNotificationFails(List<HandlingFailMessage> notificationFails) {
        this.notificationFails = notificationFails;
    }

    public List<HandlingFailMessage> getNotificationFails() {
        return notificationFails;
    }

    public void setOtherFails(List<HandlingFailMessage> otherFails) {
        this.otherFails = otherFails;
    }

    public List<HandlingFailMessage> getOtherFails() {
        return otherFails;
    }

    public void setTheFailStackTrace(String theFailStackTrace) {
        this.theFailStackTrace = theFailStackTrace;
    }

    public String getTheFailStackTrace() {
        return theFailStackTrace;
    }
}

notx/src/notx-main/src/main/java/net/notx/web/NotxActionBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.notx.web;

import net.sourceforge.stripes.action.ActionBean;
import net.sourceforge.stripes.action.ActionBeanContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Abstract parent for every NotX action beans. 
 * @author palo
 */
public abstract class NotxActionBean implements ActionBean{
     protected Logger logger = LoggerFactory.getLogger(this.getClass());
    private NotxActionBeanContext context;

    @Override
    public void setContext(ActionBeanContext context) {
        this.context = (NotxActionBeanContext) context;
    }

    @Override
    public NotxActionBeanContext getContext() {
        return context;
    }

    
}

notx/src/notx-main/src/main/java/net/notx/web/RoutingActionBean.java
package net.notx.web;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import net.notx.core.entities.RoutingRecord;
import net.notx.core.entities.RoutingRecordCollection;
import net.notx.core.entities.User;
import net.notx.core.service.UserService;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.integration.spring.SpringBean;


/**
 * 
 * @author Filip Nguyen
 */
public class RoutingActionBean extends NotxActionBean {
	
    @SpringBean
    private UserService userService;
	
	private User selectedUser = new User();
	private List<User> users = new ArrayList<User>();
	private Set<RoutingRecord> routingRecords = new TreeSet<RoutingRecord>();
	
	public Resolution show(){
		users = userService.listUsers();
		RoutingRecordCollection rrCollection = userService.loadUserRoutingRecords(selectedUser.getId());
		routingRecords=rrCollection.toListByPriority();
		return new ForwardResolution("/routing.jsp");
	}	
			
	public User getSelectedUser() {
		return selectedUser;
	}

	public void setSelectedUser(User selectedUser) {
		this.selectedUser = selectedUser;
	}

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	public Set<RoutingRecord> getRoutingRecords() {
		return routingRecords;
	}

	public void setRoutingRecords(Set<RoutingRecord> routingRecords) {
		this.routingRecords = routingRecords;
	}
}

notx/src/notx-main/src/main/java/net/notx/web/RoutingDetailActionBean.java
package net.notx.web;

import java.util.ArrayList;
import java.util.List;
import net.notx.core.entities.RoutingRecord;
import net.notx.core.entities.User;
import net.notx.core.service.TaggingService;
import net.notx.core.service.UserService;
import net.notx.web.utils.JsonUtils;
import net.sourceforge.stripes.action.DontValidate;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.Validate;
import net.sourceforge.stripes.validation.ValidateNestedProperties;

/**
 *
 * @author Filip Nguyen
 */
public class RoutingDetailActionBean extends NotxActionBean {

    @SpringBean
    private UserService userService;
    @SpringBean
    private TaggingService taggingService;
    private NotxActionBeanContext context;
    private List<User> users = new ArrayList<User>();
    private String autocompleteTags = null;
    @ValidateNestedProperties({
        @Validate(field = "priority", required = true, minvalue = 1, maxvalue = 10),
        @Validate(field = "destination", required = true, mask = "(\\w+(\\+\\w+)*)?")})
    private RoutingRecord routingRecord = new RoutingRecord();

    @DontValidate
    public Resolution preNew() {
        autocompleteTags = JsonUtils.convertToAutocomplete(taggingService.listTags());
        users = userService.listUsers();
        return new ForwardResolution("/routingDetail.jsp");
    }

    public Resolution save() {
        userService.createRoute(routingRecord);
        return new ForwardResolution(RoutingActionBean.class, "show");
    }

    @DontValidate
    public Resolution delete() {
        userService.deleteRoute(routingRecord);
        ForwardResolution fwres = new ForwardResolution(RoutingActionBean.class, "show");
        fwres.addParameter("selectedUser.id", routingRecord.getUserid());
        return fwres;
    }

    public String getAutocompleteTags() {
        return autocompleteTags;
    }

    public void setAutocompleteTags(String autocompleteTags) {
        this.autocompleteTags = autocompleteTags;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

    public RoutingRecord getRoutingRecord() {
        return routingRecord;
    }

    public void setRoutingRecord(RoutingRecord routingRecord) {
        this.routingRecord = routingRecord;
    }
}

notx/src/notx-main/src/main/java/net/notx/web/TemplateActionBean.java
package net.notx.web;

import net.notx.core.entities.SuperTemplate;
import net.notx.core.entities.Template;
import net.notx.core.entities.TemplateDescriptor;
import net.notx.core.service.TemplateService;
import net.sourceforge.stripes.action.DontValidate;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.integration.spring.SpringBean;


/**
 *
 * @author Filip Nguyen
 */
public class TemplateActionBean extends NotxActionBean {

    @SpringBean
    private TemplateService templateService;
    // -- Bean properties
    private SuperTemplate superTemplate = new SuperTemplate();
    private TemplateDescriptor descriptor = new TemplateDescriptor();
    private Template template = new Template();

    @DontValidate
    public Resolution show() {
        superTemplate = templateService.loadTemplate(superTemplate.getName());
        template = superTemplate.getTemplate(descriptor);
        return new ForwardResolution("/template.jsp");
    }

    @DontValidate
    public Resolution delete() {
        superTemplate = templateService.loadTemplate(superTemplate.getName());
        superTemplate.remove(descriptor);
        templateService.deleteTemplate(superTemplate);
        templateService.createTemplate(superTemplate);

        ForwardResolution fwres = new ForwardResolution(SuperTemplateActionBean.class, "show");
        fwres.addParameter("selectedSuperTemplate.name", superTemplate.getName());
        return fwres;
    }

    @DontValidate
    public Resolution preNew() {
        return new ForwardResolution("/template.jsp");
    }

    public Resolution save() {
        superTemplate = templateService.loadTemplate(superTemplate.getName());
        superTemplate.addTemplate(descriptor, template);
        templateService.createTemplate(superTemplate);
        return show();
    }

    public SuperTemplate getSuperTemplate() {
        return superTemplate;
    }

    public void setSuperTemplate(SuperTemplate superTemplate) {
        this.superTemplate = superTemplate;
    }

    public TemplateDescriptor getDescriptor() {
        return descriptor;
    }

    public void setDescriptor(TemplateDescriptor descriptor) {
        this.descriptor = descriptor;
    }

    public Template getTemplate() {
        return template;
    }

    public void setTemplate(Template template) {
        this.template = template;
    }
}

notx/src/notx-main/src/main/java/net/notx/web/UtilityActionBean.java
package net.notx.web;

import net.notx.cassandra.CassandraException;
import net.notx.core.service.InitService;
import net.sourceforge.stripes.action.DontValidate;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.integration.spring.SpringBean;

/**
 * @author Filip Nguyen
 */
public class UtilityActionBean extends NotxActionBean {

    @SpringBean
    private InitService initService;

    @DontValidate
    public Resolution show() throws CassandraException {
        return new ForwardResolution("/index.jsp");
    }

    public boolean isInitialized() {
        return initService.isInitialized();
    }

    public Resolution initialize() {
        initService.initialize();
        return new ForwardResolution("/index.jsp");
    }
}

notx/src/notx-main/src/main/webapp/cassandraDown.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>


<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
		  	<h1>Cassandra is probably down</h1>
		    Cannot connect cassandra on address: ${actionBean.cassandraSettings}. Please check that cassandra database is online.
		      
	  </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/domainStats.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>


<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
		  	<h1>All sent notifications</h1>
		    <stripes:errors/>
		    <c:forEach items="${actionBean.statisticsByDomain}" var="stats" varStatus="rowstat">
			    <h2> <td>${stats.key}</td> </h2>
					<table class="elegant-table">
					 <thead>
						<tr> 
							<th>Sent time</th>
							<th>Engine</th>
							<th>Contact</th>
							<th>Correlation time</th>
						</tr>
					</thead>
		      <tbody>
						<c:forEach items="${stats.value}" var="stat" varStatus="rowstat">
					    <tr class="${rowstat.count mod 2 == 0 ? "even" : "odd"} ${empty stat.receivedTime ? "not-correlated" : "correlated"}">
					     	<td><fmt:formatDate value="${stat.time}" pattern="MM.dd HH:mm" /></td>
					     	<td>${stat.engine}</td>
					     	<td>${stat.contact}</td>
					     	<td><fmt:formatDate value="${stat.correlationTime}" pattern="MM.dd HH:mm" /></td>
					    </tr>
				    </c:forEach>
				   </tbody>
					</table>
				</c:forEach>    
				<br/>
				<img src="${actionBean.graph}"/>
    </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/errorView.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>


<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
		  	<h1>Errors</h1>
		    <stripes:errors/>
		    <h2>Failed notifications</h2>
				<table class="elegant-table">
						 <thead>
							<tr> 
								<th>Type</th>
								<th>Context</th>
								<th>JMS cause</th>
								<th>Exception info</th>
								<th></th>
							</tr>
						</thead>
			       <tbody>
						    <c:forEach items="${actionBean.notificationFails}" var="nf" varStatus="rowstat">
						     <tr>
						       <td>${nf.type}</td>
						       <td>${nf.errorCause}</td>
						       <td>${nf.sqsMessage}</td>
						       <td>${nf.exceptionInfo}</td>
						       <td>	
						       			<stripes:link href="/ErrorView.action" event="viewDetail">
						        	    	Detail
						       	    	  <stripes:param name="detail.uid" value="${nf.uid}"/>
						          	</stripes:link>
		               </td>
						     </tr>
						    </c:forEach>
					   </tbody>
				</table>
						<stripes:link href="/ErrorView.action" event="resendNotifications">
		            	Send all to MQ again
            </stripes:link>
		    <h2>Others</h2>
				<table  class="elegant-table">
						 <thead>
							<tr> 
								<th>Type</th>
								<th>Error cause</th>
								<th>JMS</th>
								<th>Stack trace</th>
							</tr>
						</thead>
			       <tbody>
						    <c:forEach items="${actionBean.otherFails}" var="of" varStatus="rowstat">
						     <tr>
						       <td>${of.type}</td>
						       <td>${of.errorCause}</td>
						       <td>${of.sqsMessage}</td>
						       <td>${of.stackTrace}</td>
						     </tr>
						    </c:forEach>
					   </tbody>
				</table>
						<stripes:link href="/ErrorView.action" event="resendOthers">
				            	Send all to MQ again
            </stripes:link>
    </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/errorViewDetail.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>


<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
		  	<h1>Detail of fail</h1>
		    <stripes:errors/>
		    <stripes:link href="/ErrorView.action" event="sendNotificationToMQ">Send message back to MQ
		      <stripes:param name="detail.uid" value="${actionBean.detail.uid}"/>
		    </stripes:link>
		    <h2>JMS message that caused error</h2>
				${actionBean.detail.jmsMessage}
				<h2>Stack trace</h2>
				${actionBean.theFailStackTrace}  
	  </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/index.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>

<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
    <h1>NotX utility</h1>
    <c:choose>
        <c:when test="${actionBean.initialized}">
            <p>Service initialized</p>
            <stripes:link beanclass="net.notx.web.UtilityActionBean" event="initialize">Reinitialize</stripes:link>
        </c:when>
        <c:otherwise>
            	<stripes:link beanclass="net.notx.web.UtilityActionBean" event="initialize">Initialize</stripes:link>
        </c:otherwise>
    </c:choose>
    
    </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/jmsDown.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>


<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
		  	<h1>JMS malfunction</h1>
		    Cannot connect JMS brooker on address: ${actionBean.jmsSettings}. Please check that JMS brooker is working.
		      
	  </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/routing.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>

<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="documentReady">
          $('#selectedUserID').change(function() {
              $('#formListOfRR').submit();
          });
    </stripes:layout-component>
    <stripes:layout-component name="contents">
        <h1>Routing records</h1>
        <stripes:errors/>
        
        <stripes:link href="/RoutingDetail.action" event="preNew">New routing record</stripes:link>
     
        <h2>List of routing records</h2>
        <stripes:form id="formListOfRR" action="/Routing.action" focus="">
           <stripes:select id="selectedUserID" name="selectedUser.id">
              <stripes:option value="">Global routing records</stripes:option>
              <stripes:options-collection collection="${actionBean.users}"
                                          label="name" value="id"/>
           </stripes:select>
        </stripes:form>
        <table class="elegant-table">
				 <thead>
					<tr>
					  <th>For user</th> 
						<th>Priority</th>
						<th>Source</th>
						<th>Destionation</th>
						<th>Message type</th>
						<th></th>
					</tr>
				 </thead>
				 <tbody>
		    	<c:forEach items="${actionBean.routingRecords}" var="rr" varStatus="rowstat">
			    	<tr class="${rowstat.count mod 2 == 0 ? "even" : "odd"}">
			      	<td>${rr.userid}</td>
			      	<td>${rr.priority}</td>
			      	<td>${rr.source}</td>
			      	<td>${rr.destination}</td>
			      	<td>${rr.msgtype}</td>
			      	<td><stripes:link  href="/RoutingDetail.action" event="delete">
			      	      delete
			      	      <stripes:param name="routingRecord.recordid" value="${rr.recordid}"/>
			      	      <stripes:param name="routingRecord.userid" value="${rr.userid}"/>
			      	    </stripes:link></td>
			      </tr>
					</c:forEach>
					</tbody>
				</table> 
    </stripes:layout-component>
</stripes:layout-render>

notx/src/notx-main/src/main/webapp/usersDetail.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ include file="/layout/taglibs.jsp" %>


<stripes:layout-render name="/layout/notx_utility_layout.jsp">
    <stripes:layout-component name="contents">
		  	<h1>User</h1>
		    <stripes:errors/>
			  <table>
				    <stripes:form action="/UsersDetail.action" focus="">
				    <tbody>
			     		<tr><td><stripes:label for="user.id"/> </td><td><stripes:text name="user.id"/></td></tr>
			     		<tr><td><stripes:label for="user.name"/></td><td><stripes:text  name="user.name"/></td></tr>
			        <tr><td><stripes:label for="user.lang"/></td><td><stripes:text  name="user.lang"/></td></tr>
			        <tr><td><stripes:label for="contacts"/> </td><td><stripes:textarea name="user.contacts"/></td></tr>
			        <tr><td colspan="2"><stripes:submit name="save" value="Save"/></td></tr>
			       </tbody>
						</stripes:form>
				</table>    
    </stripes:layout-component>
</stripes:layout-render>